title: Louise Dubois de Prisque
description: PhD student, Inria Saclay
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions

github:
  repository_url: https://github.com/louiseddp
